# Generated by Django 5.2.7 on 2025-11-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='status',
            new_name='payment_status',
        ),
    ]
